wallpaper {
    monitor = LVDS-1
    path = ~/STUFF/Thomas Cole - Architect’s Dream.jpg
    fit_mode = cover
}
wallpaper {
    monitor = VGA-1
    path = ~/STUFF/The Sun Sets Sail.webp
    fit_mode = cover
}

    splash = false
